- name: "loremjs"
  runtimefs: "nodejs.ext4"
  appfs: "loremjs.ext4"
  vcpus: 1
  memory: 128
  concurrency_limit: 1
  load_dir: "./images/snapshots/nodejs-128"
- name: "lorempy2"
  runtimefs: "python2.ext4"
  appfs: "lorempy2.ext4"
  vcpus: 1
  memory: 128
  concurrency_limit: 1
  load_dir: "./images/snapshots/python2-128"
- name: "autocomplete"
  runtimefs: "nodejs.ext4"
  appfs: "autocomplete.ext4"
  vcpus: 1
  memory: 256
  concurrency_limit: 600
  load_dir: "./images/snapshots/autocomplete-128"
- name: "img-resize"
  runtimefs: "nodejs.ext4"
  appfs: "img-resize.ext4"
  vcpus: 1
  memory: 512
  concurrency_limit: 600
  load_dir: "./images/snapshots/img-resize-512"
- name: "markdown-to-html"
  runtimefs: "python2.ext4"
  appfs: "markdown-to-html.ext4"
  vcpus: 1
  memory: 256
  concurrency_limit: 1000
  load_dir: "./images/snapshots/markdown-to-html-256"
- name: "ocr-img"
  runtimefs: "nodejs.ext4"
  appfs: "ocr-img.ext4"
  vcpus: 1
  memory: 256
  concurrency_limit: 600
  load_dir: "./images/snapshots/ocr-img-1024"
- name: "sentiment-analysis"
  runtimefs: "python2.ext4"
  appfs: "sentiment-analysis.ext4"
  vcpus: 1
  memory: 256
  concurrency_limit: 600
  load_dir: "./images/snapshots/sentiment-analysis-128"
